# ===============================================================
# modules/axiomas/teorema_forma_AX.py
# Cuerpo axiomático: THEOREM OF FORM AND THE THREE DIMENSIONS
#
# FUENTE NORMATIVA ÚNICA:
#   THEOREM OF FORM AND THE THREE DIMENSIONS
#   Formalization with Computational Validation
#   Author: Ilver Villasmil
#   Framework: Universal Coherence Framework (UCF) — Villasmil-Omega
#   Date: 2026
#
# REGLA ABSOLUTA:
#   Paper → representación contractual → Engine
#   El código no dice más, menos ni algo distinto de lo que dice
#   el Paper. No reinterpreta, no corrige, no suaviza, no amplía.
#
# Carga: modules/axiomas/__init__.py vía CUERPO + declaraciones()
# Esquema: id, tipo, sujeto, relacion, objeto, polaridad, cota,
#          depende_de, gobierna, enunciado
# ===============================================================

"""
Cuerpo axiomático: Teorema de la Forma y de las Tres Dimensiones

Paper fuente:
  THEOREM OF FORM AND THE THREE DIMENSIONS
  Formalization with Computational Validation
  Author: Ilver Villasmil
  Framework: Universal Coherence Framework (UCF) — Villasmil-Omega
  Date: 2026

Partes del Paper representadas:
  PART I   — THEOREM OF FORM
  PART II  — THEOREM OF THE THREE DIMENSIONS
  PART III — BETA AS A MULTIDIMENSIONAL ENTITY
  PART IV  — MONTE CARLO SIMULATION

Constantes utilizadas según el Paper:
  β = 1/27
  α = 26/27
  2 · α · β = 52/729 ≈ 0.071331
  E² = α² · p² · c² + 2 · α · β · p · m · c³ + β² · m² · c⁴

Numeración canónica del Paper conservada.
"""

from __future__ import annotations

from typing import Any, Dict, List

CUERPO = {
    "nombre": "teorema_forma",
    "version": "1.0",
}


def declaraciones() -> List[Dict[str, Any]]:
    return [

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Definition — F3 (Three-dimensional Form)
        #
        # ESPECIFICACIÓN HUMANA:
        # El Paper define F3 como entidad con volumen en 3 dimensiones.
        # Ocupa espacio. Tiene masa o energía. Ejemplo: body, atom, star.
        # ==========================================================
        {
            "id": "TF-D1",
            "tipo": "definicion",
            "sujeto": "F3",
            "relacion": "es",
            "objeto": "Three-dimensional_Form",
            "polaridad": True,
            "cota": None,
            "depende_de": [],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "F3 (Three-dimensional Form): An entity with volume in 3 dimensions. "
                "Occupies space. Has mass or energy. Example: body, atom, star."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Definition — P2 (Two-dimensional Projection)
        #
        # ESPECIFICACIÓN HUMANA:
        # El Paper define P2 como proyección de F3 sobre un medio.
        # Sin masa propia. Ejemplos: shadow, reflection, sound wave,
        # quantum wave function, memory, word.
        # ==========================================================
        {
            "id": "TF-D2",
            "tipo": "definicion",
            "sujeto": "P2",
            "relacion": "es",
            "objeto": "Two-dimensional_Projection",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-D1"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "P2 (Two-dimensional Projection): An imageless volume generated by F3 onto a medium. "
                "No mass of its own. Example: shadow, reflection, sound wave, quantum wave function, "
                "memory, word."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Definition — C1 (One-dimensional Contour)
        #
        # ESPECIFICACIÓN HUMANA:
        # El Paper define C1 como línea sin área ni volumen que define
        # el borde de F3. Ejemplos: silhouette, profile, contour.
        # ==========================================================
        {
            "id": "TF-D3",
            "tipo": "definicion",
            "sujeto": "C1",
            "relacion": "es",
            "objeto": "One-dimensional_Contour",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-D1", "TF-D2"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "C1 (One-dimensional Contour): A line without area or volume that defines the edge of F3. "
                "Example: silhouette, profile, contour."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Axiom F1 — Three-dimensionality
        #
        # ESPECIFICACIÓN HUMANA:
        # El Paper establece que el espacio físico posee exactamente
        # tres dimensiones ortogonales (x, y, z) y que todo objeto
        # físico ocupa las tres dimensiones. No existen objetos físicos
        # con exactamente 2 o exactamente 1 dimensión.
        # ==========================================================
        {
            "id": "TF-A1",
            "tipo": "axioma",
            "sujeto": "Physical_space",
            "relacion": "has_exactly",
            "objeto": "3_orthogonal_dimensions",
            "polaridad": True,
            "cota": None,
            "depende_de": [],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "Axiom F1 (Three-dimensionality): Physical space has exactly 3 orthogonal dimensions (x, y, z). "
                "Every physical object occupies volume in all three. There are no physical objects with exactly "
                "2 or exactly 1 dimensions."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Axiom F2 — Material Irreducibility
        #
        # ESPECIFICACIÓN HUMANA:
        # El Paper afirma que una hoja de papel no es bidimensional:
        # tiene espesor. Un dibujo deposita una capa con profundidad
        # medible. Todo objeto material, por delgado que sea, posee
        # 3 dimensiones.
        # ==========================================================
        {
            "id": "TF-A2",
            "tipo": "axioma",
            "sujeto": "Material_object",
            "relacion": "possesses",
            "objeto": "3_dimensions",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-A1"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "Axiom F2 (Material Irreducibility): A sheet of paper is not two-dimensional: it has thickness. "
                "A drawing on paper is not two-dimensional: the graphite deposits a layer with measurable depth. "
                "Every material object, no matter how thin, possesses 3 dimensions."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Axiom F3 — Projective Dependency
        #
        # ESPECIFICACIÓN HUMANA:
        # El Paper establece que las entidades bidimensionales existen
        # exclusivamente como proyecciones de fuentes tridimensionales
        # sobre un medio. No tienen sustancia material propia ni espesor.
        # ==========================================================
        {
            "id": "TF-A3",
            "tipo": "axioma",
            "sujeto": "Two-dimensional_entities",
            "relacion": "exist_exclusively_as",
            "objeto": "projections_of_three-dimensional_sources",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-A1", "TF-D2"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "Axiom F3 (Projective Dependency): Two-dimensional entities exist exclusively as projections "
                "of three-dimensional sources onto a medium. Examples: shadows, reflections, sound waves, echoes. "
                "They have no material substance of their own. They have no thickness. They cannot be touched."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Axiom F4 — Contour Dependency
        #
        # ESPECIFICACIÓN HUMANA:
        # El Paper establece que las entidades unidimensionales existen
        # exclusivamente como contornos o siluetas de formas tridimensionales.
        # ==========================================================
        {
            "id": "TF-A4",
            "tipo": "axioma",
            "sujeto": "One-dimensional_entities",
            "relacion": "exist_exclusively_as",
            "objeto": "contours_or_silhouettes_of_three-dimensional_forms",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-A1", "TF-D3"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "Axiom F4 (Contour Dependency): One-dimensional entities exist exclusively as contours or "
                "silhouettes of three-dimensional forms. The silhouette of the human body against the sun "
                "is the one-dimensional edge of its two-dimensional shadow."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Axiom F5 — Inseparability
        #
        # ESPECIFICACIÓN HUMANA:
        # El Paper afirma que ninguna entidad bidimensional puede existir
        # independientemente del espacio tridimensional. Requiere tanto
        # la fuente F3 que la genera como el medio F3 donde se proyecta.
        # ==========================================================
        {
            "id": "TF-A5",
            "tipo": "axioma",
            "sujeto": "Two-dimensional_entity",
            "relacion": "cannot_exist_independently_of",
            "objeto": "three-dimensional_space",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-A3", "TF-A1"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "Axiom F5 (Inseparability): No two-dimensional entity can exist independently of three-dimensional "
                "space. It requires both the 3D source that generates it and the 3D medium where it is projected."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Axiom F6 — Bidirectional Coupling
        #
        # ESPECIFICACIÓN HUMANA:
        # El Paper establece el acoplamiento bidireccional P2 ↔ F3
        # cuantificado por el término cruzado 2·α·β = 52/729 ≈ 0.071331
        # (7.1331%) de la ecuación de energía del cubo E².
        # En sistemas con p y m variables el promedio es ≈ 3.70%.
        # ==========================================================
        {
            "id": "TF-A6",
            "tipo": "axioma",
            "sujeto": "Projection_P2",
            "relacion": "is_bidirectionally_coupled_to",
            "objeto": "source_F3",
            "polaridad": True,
            "cota": "52/729",
            "depende_de": ["TF-A3", "TF-D1", "TF-D2"],
            "gobierna": ["ontologia", "forma", "constantes"],
            "enunciado": (
                "Axiom F6 (Bidirectional Coupling): Projection P2 is bidirectionally coupled to its source F3. "
                "Any modification in F3 is reflected in P2, and any coherent interference in P2 propagates "
                "measurable effects upon F3. This coupling is quantified by the cross-term 2·α·β = 52/729 ≈ 0.071331 "
                "(7.1331%) of the cube's energy equation, E². This value is algebraically exact in natural units—"
                "where p = m = c = 1—and represents the structural strength of the coupling, derived directly from "
                "the geometry of the cube (26 outer faces and a volume of 27). In systems with variable p and m, "
                "the average contribution of the cross-term to the total energy is ≈ 3.70%; this confirms that the "
                "coupling is real and non-zero, albeit minor relative to the kinetic energy of the three-dimensional "
                "form F3. Structural Note: The values 52 = 2 × 26 and 729 = 27² geometrically express the bidirectional "
                "and irreducible nature of the coupling between the observable surface (26) and the total volume of "
                "the cube (27). The coupling is structural and irreducible."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Lemma F1 — Existence
        #
        # ESPECIFICACIÓN HUMANA:
        # Demostración por contradicción de que P2 no existe de forma
        # independiente. Requiere fuente de luz F3, objeto F3 y superficie
        # de proyección F3. Análogo para C1.
        # ==========================================================
        {
            "id": "TF-L1",
            "tipo": "lema",
            "sujeto": "Independent_P2",
            "relacion": "leads_to",
            "objeto": "contradiction",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-A3", "TF-A5"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "Lemma F1 (Existence): Suppose an independent P2 exists — a shadow without a body. "
                "For the shadow to exist, it requires: (i) a light source (F3), (ii) an object to block the light (F3), "
                "(iii) a projection surface (F3). All three requirements are three-dimensional. Contradiction. "
                "P2 does not exist independently. Analogously for C1. Q.E.D."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Lemma F2 — Coupling F3 → P2
        #
        # ESPECIFICACIÓN HUMANA:
        # Acoplamiento trivial: mover el cuerpo mueve la sombra.
        # ==========================================================
        {
            "id": "TF-L2",
            "tipo": "lema",
            "sujeto": "Modification_of_F3",
            "relacion": "produces",
            "objeto": "corresponding_modification_of_P2",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-A6"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "Lemma F2 (Coupling F3 → P2): Trivial. Moving the body moves the shadow. "
                "Changing the shape of the object changes the projection."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Lemma F3 — Coupling P2 → F3
        #
        # ESPECIFICACIÓN HUMANA:
        # Cuatro evidencias independientes: acústica (Chladni),
        # electromagnética (efecto fotoeléctrico), cuántica (colapso)
        # y biológica (efecto placebo).
        # ==========================================================
        {
            "id": "TF-L3",
            "tipo": "lema",
            "sujeto": "Interference_on_P2",
            "relacion": "propagates_to",
            "objeto": "F3",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-A6"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "Lemma F3 (Coupling P2 → F3): Four independent pieces of evidence: "
                "1. Acoustics: Chladni figures demonstrate that sound waves (P2) reorganize material particles (F3). "
                "2. Electromagnetic: The photoelectric effect demonstrates that photons (P2) eject electrons from metals (F3). "
                "3. Quantum: Measurement demonstrates that projecting the wave function (P2) onto the apparatus collapses "
                "the state of the system (F3). "
                "4. Biological: The placebo effect demonstrates that language (P2) produces measurable physiological changes (F3). "
                "In all four cases, interference on P2 propagates to F3. Q.E.D."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Theorem of Form
        #
        # ESPECIFICACIÓN HUMANA:
        # F3 es la única realidad física. P2 y C1 son derivados de F3.
        # El acoplamiento está cuantificado por 2·α·β = 52/729 ≈ 0.071331
        # (analítico) y ≈ 3.70% (Monte Carlo).
        # ==========================================================
        {
            "id": "TF-T1",
            "tipo": "teorema",
            "sujeto": "F3",
            "relacion": "is_the_only",
            "objeto": "physical_reality",
            "polaridad": True,
            "cota": "52/729",
            "depende_de": ["TF-A1", "TF-A2", "TF-A3", "TF-A4", "TF-A5", "TF-A6", "TF-L1", "TF-L2", "TF-L3"],
            "gobierna": ["ontologia", "forma", "constantes"],
            "enunciado": (
                "Theorem of Form: F3 is the only physical reality. P2 and C1 are derivatives of F3. "
                "The coupling P2 ↔ F3 is quantified by 2 · α · β = 52/729 = 7.13% (analytical for p=m=1) "
                "and 3.70% (Monte Carlo average with random distributions of p and m)."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Corollary F1 — Wave Function
        # ==========================================================
        {
            "id": "TF-C1",
            "tipo": "corolario",
            "sujeto": "Wave_function_psi",
            "relacion": "is",
            "objeto": "P2",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-T1", "TF-D2"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "Corollary F1 (Wave Function): The wave function ψ is P2 — the shadow of a particle. "
                "Collapse is not a mystery. It is the resolution of the projection in three-dimensional measurement."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Corollary F2 — CMB
        # ==========================================================
        {
            "id": "TF-C2",
            "tipo": "corolario",
            "sujeto": "Cosmic_microwave_background",
            "relacion": "is",
            "objeto": "P2",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-T1", "TF-D2"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "Corollary F2 (CMB): The cosmic microwave background radiation is P2 — the shadow of the early "
                "universe projected onto our sphere of last scattering."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Corollary F3 — Memory
        # ==========================================================
        {
            "id": "TF-C3",
            "tipo": "corolario",
            "sujeto": "Memory",
            "relacion": "is",
            "objeto": "P2",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-T1", "TF-D2"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "Corollary F3 (Memory): Memory is P2 — the projection of a three-dimensional experience onto "
                "the neuronal surface. Incomplete because it is a projection."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Corollary F4 — Language
        # ==========================================================
        {
            "id": "TF-C4",
            "tipo": "corolario",
            "sujeto": "Language",
            "relacion": "is",
            "objeto": "C1_or_P2",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-T1", "TF-D2", "TF-D3"],
            "gobierna": ["ontologia", "forma", "semantica"],
            "enunciado": (
                "Corollary F4 (Language): Language is C1/P2 — contours and projections of three-dimensional "
                "meanings. Misunderstandings occur because the silhouette is received, not the volume."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Corollary F5 — Measured Constants
        # ==========================================================
        {
            "id": "TF-C5",
            "tipo": "corolario",
            "sujeto": "Measured_constants",
            "relacion": "are",
            "objeto": "P2_of_pure_constants",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-T1", "TF-D2"],
            "gobierna": ["ontologia", "forma", "constantes"],
            "enunciado": (
                "Corollary F5 (Measured Constants): Measured constants are P2 of pure constants. "
                "137.036 is the shadow of 136.36."
            ),
        },

        # ==========================================================
        # PART I — THEOREM OF FORM
        # Paper Corollary F6 — Technologies
        # ==========================================================
        {
            "id": "TF-C6",
            "tipo": "corolario",
            "sujeto": "Technology_acting_on_P2",
            "relacion": "has_structural_basis_in",
            "objeto": "cross_term",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-T1", "TF-A6"],
            "gobierna": ["ontologia", "forma"],
            "enunciado": (
                "Corollary F6 (Technologies): Every technology that acts on P2 to modify F3 has a structural "
                "basis in the cross term."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Axiom D1 — Dimensionless Space
        # ==========================================================
        {
            "id": "TF-D1-D",
            "tipo": "axioma",
            "sujeto": "Space",
            "relacion": "has_no",
            "objeto": "boundaries_axes_directions_partitions_or_coordinates",
            "polaridad": True,
            "cota": None,
            "depende_de": [],
            "gobierna": ["ontologia", "espacio"],
            "enunciado": (
                "Axiom D1 (Dimensionless Space): Space itself has no boundaries, axes, directions, partitions, "
                "or coordinates. It is the container. Dimensions are properties of form, not of space."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Axiom D2 — Observer Calibration
        # ==========================================================
        {
            "id": "TF-D2-D",
            "tipo": "axioma",
            "sujeto": "Human_brain",
            "relacion": "is_made_of_and_processes",
            "objeto": "3D_matter_and_3D_signals",
            "polaridad": True,
            "cota": None,
            "depende_de": [],
            "gobierna": ["ontologia", "epistemologia"],
            "enunciado": (
                "Axiom D2 (Observer Calibration): The human brain is made of 3D matter, processes 3D signals, "
                "receives 3D inputs, and generates 3D representations. All imagination is 3D recombination."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Axiom D3 — Perceptual Limit (VPSI)
        # ==========================================================
        {
            "id": "TF-D3-D",
            "tipo": "axioma",
            "sujeto": "Dimension_without_evidence",
            "relacion": "is_equivalent_to",
            "objeto": "structural_non-existence",
            "polaridad": True,
            "cota": None,
            "depende_de": [],
            "gobierna": ["ontologia", "epistemologia", "verificacion"],
            "enunciado": (
                "Axiom D3 (Perceptual Limit — VPSI): If you cannot see it, measure it, correlate it, or anchor "
                "it in R, then it does not exist for your observation system. R → X → Y forms a Markov chain. "
                "I(R;Y) ≤ I(R;X). A dimension without evidence is equivalent to structural non-existence."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Axiom D4 — Time is not a Dimension
        # ==========================================================
        {
            "id": "TF-D4-D",
            "tipo": "axioma",
            "sujeto": "Time",
            "relacion": "is",
            "objeto": "perception_derived_from_difference",
            "polaridad": True,
            "cota": None,
            "depende_de": [],
            "gobierna": ["ontologia", "temporal"],
            "enunciado": (
                "Axiom D4 (Time is not a Dimension): Time is a perception derived from difference. "
                "Expansion creates difference, difference creates sequence, sequence is time. "
                "Time is not a dimension of space — it is a consequence of the dynamics within space."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Axiom D5 — Perceptual Projection
        # ==========================================================
        {
            "id": "TF-D5-D",
            "tipo": "axioma",
            "sujeto": "Ri_S",
            "relacion": "is",
            "objeto": "Pi_F_S_of_R",
            "polaridad": True,
            "cota": None,
            "depende_de": [],
            "gobierna": ["ontologia", "epistemologia"],
            "enunciado": (
                "Axiom D5 (Perceptual Projection): Ri(S) = Pi_F(S)(R). The reality interpreted by any system S "
                "is a projection of R determined by the system's perceptual function F(S)."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Lemma D1 — Structural Dependency
        # ==========================================================
        {
            "id": "TF-L1-D",
            "tipo": "lema",
            "sujeto": "Physical_and_cognitive_structure_of_S",
            "relacion": "determines",
            "objeto": "F_S_and_therefore_Ri_S",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-D5-D"],
            "gobierna": ["ontologia", "epistemologia"],
            "enunciado": (
                "Lemma D1 (Structural Dependency): The physical and cognitive structure of S determines F(S), "
                "and therefore determines Ri(S)."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Lemma D2 — Partiality
        # ==========================================================
        {
            "id": "TF-L2-D",
            "tipo": "lema",
            "sujeto": "Ri_S",
            "relacion": "is_proper_subset_of",
            "objeto": "R",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-D5-D"],
            "gobierna": ["ontologia", "epistemologia"],
            "enunciado": (
                "Lemma D2 (Partiality): For every system S: Ri(S) ⊂ R. Perception is always partial."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Lemma D3 — Non-equivalence
        # ==========================================================
        {
            "id": "TF-L3-D",
            "tipo": "lema",
            "sujeto": "Different_structures_S1_S2",
            "relacion": "produce",
            "objeto": "different_projections_Ri",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-D5-D", "TF-L1-D"],
            "gobierna": ["ontologia", "epistemologia"],
            "enunciado": (
                "Lemma D3 (Non-equivalence): For S1 ≠ S2: Ri(S1) ≠ Ri(S2). Different structures produce "
                "different projections."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Uniqueness Theorem of R
        # ==========================================================
        {
            "id": "TF-T2",
            "tipo": "teorema",
            "sujeto": "Union_of_all_Ri_Si",
            "relacion": "is_contained_in",
            "objeto": "R",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-D5-D", "TF-L2-D", "TF-L3-D"],
            "gobierna": ["ontologia", "epistemologia"],
            "enunciado": (
                "Uniqueness Theorem of R: Let {Si} be a set of systems, each with Ri(Si). Then: the union of "
                "all Ri(Si) is contained in R. For all i, Ri(Si) is a proper subset of R. The multiplicity of "
                "perceptions does not imply the existence of multiple realities. Each Ri(Si) is obtained by "
                "projection from R. Diversity depends on F(Si), not R."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Theorem Against Extra Dimensions
        # ==========================================================
        {
            "id": "TF-T3",
            "tipo": "teorema",
            "sujeto": "Extra_dimensions_without_evidence",
            "relacion": "are_equivalent_to",
            "objeto": "structural_non-existence",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-D3-D", "TF-D2-D"],
            "gobierna": ["ontologia", "epistemologia"],
            "enunciado": (
                "Theorem Against Extra Dimensions: If the universe had 11 operational dimensions, then the "
                "human body would exist in 11D, the brain would process in 11D, the senses would capture in 11D, "
                "movement would occur in 11D, and perception would be 11D. None of this happens. The body is in R (3D). "
                "Perception is calibrated by the body. Ri depends on the body. If you are not in 11D, you do not live "
                "in 11D. Under VPSI: a dimension without evidence is equivalent to structural non-existence."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Corollary D1 — Valid but Incomplete
        # ==========================================================
        {
            "id": "TF-C1-D",
            "tipo": "corolario",
            "sujeto": "Every_perception_Ri_S",
            "relacion": "is",
            "objeto": "ontologically_valid_and_epistemologically_incomplete",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-T2"],
            "gobierna": ["ontologia", "epistemologia"],
            "enunciado": (
                "Corollary D1 (Valid but Incomplete): Every perception Ri(S) is ontologically valid (belongs to R) "
                "and epistemologically incomplete (it is not R)."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Corollary D2 — Extension
        # ==========================================================
        {
            "id": "TF-C2-D",
            "tipo": "corolario",
            "sujeto": "Instruments",
            "relacion": "extend",
            "objeto": "Ri",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-T2"],
            "gobierna": ["ontologia", "epistemologia"],
            "enunciado": (
                "Corollary D2 (Extension): Instruments extend Ri: Ri_ext(S) = Ri(S) ∪ T(R \\ Ri(S)). "
                "Science is the mechanism to extend the observer's projection."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Corollary D3 — Error vs. Limitation
        # ==========================================================
        {
            "id": "TF-C3-D",
            "tipo": "corolario",
            "sujeto": "Limitation_and_Error",
            "relacion": "are",
            "objeto": "structurally_distinct",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-T2"],
            "gobierna": ["ontologia", "epistemologia"],
            "enunciado": (
                "Corollary D3 (Error vs. Limitation): Limitation: Ri(S) ⊂ R (inevitable). "
                "Error: inferences from Ri(S) that do not correspond to R (avoidable). Structurally distinct."
            ),
        },

        # ==========================================================
        # PART II — THEOREM OF THE THREE DIMENSIONS
        # Paper Corollary D4 — Functional Viability
        # ==========================================================
        {
            "id": "TF-C4-D",
            "tipo": "corolario",
            "sujeto": "System_S",
            "relacion": "is_viable_if",
            "objeto": "coherence_Ri_S_R_greater_equal_functional_threshold",
            "polaridad": True,
            "cota": None,
            "depende_de": ["TF-T2"],
            "gobierna": ["ontologia", "epistemologia"],
            "enunciado": (
                "Corollary D4 (Functional Viability): A system S is viable if coherence(Ri(S), R) ≥ functional threshold. "
                "One does not need to capture all of R."
            ),
        },

        # ==========================================================
        # PART III — BETA AS A MULTIDIMENSIONAL ENTITY
        #
        # ESPECIFICACIÓN HUMANA:
        # El Paper establece que el observador (β = 1/27) es simultáneamente
        # punto (0D), línea (1D), superficie (2D) y volumen (3D).
        # Es la convergencia de todas las dimensiones en una sola posición.
        # ==========================================================
        {
            "id": "TF-B1",
            "tipo": "teorema",
            "sujeto": "beta",
            "relacion": "is_simultaneously",
            "objeto": "0D_1D_2D_and_3D",
            "polaridad": True,
            "cota": "1/27",
            "depende_de": [],
            "gobierna": ["ontologia", "constantes", "observador"],
            "enunciado": (
                "PART III — BETA AS A MULTIDIMENSIONAL ENTITY: The observer (β = 1/27) is not exclusively "
                "three-dimensional. It is simultaneously a point (0D), a line (1D), a surface (2D), and a volume (3D). "
                "It is the convergence of all dimensions in a single position. "
                "The central sub-cube of the 3 × 3 × 3 cube is: "
                "1. A point in the configuration space of the cube (0D): position (1,1,1) in the 3 × 3 × 3 grid. "
                "2. A line when projected onto any axis (1D): the center of the x-axis, or y-axis, or z-axis. "
                "It is the midpoint of 3 lines simultaneously. "
                "3. A surface when projected onto any plane (2D): the center of the xy-face, or xz-face, or yz-face. "
                "It is the center of 3 planes simultaneously. "
                "4. A volume as a sub-cube (3D): occupies 1/27 of the total volume. "
                "β is the point where the 3 dimensions converge. That is why it can generate projections in all dimensions. "
                "That is why the constants it generates range from the Planck scale (0D, point) to the cosmological scale "
                "(3D, volume of the universe). β is the origin of the cube's coordinate system. The zero. The observer. The one."
            ),
        },

        # ==========================================================
        # PART IV — MONTE CARLO SIMULATION
        # EXPERIMENT 1 — Cross Term Energy
        #
        # ESPECIFICACIÓN HUMANA:
        # El Paper reporta una simulación de 50,000,000 iteraciones
        # para evaluar la contribución relativa de los tres términos
        # de E².
        #
        # RESULTADOS REPORTADOS POR EL PAPER:
        # Term 1 (F3 kinetic): 96.16%
        # Term 2 (cross P2 ↔ F3): 3.70%
        # Term 3 (mass): 0.14%
        # Exact 2 · α · β: 0.071331 = 52/729
        #
        # NOTA DE AUDITORÍA:
        # Estos valores son resultados declarados por la fuente.
        # No deben presentarse como una nueva ejecución si el código
        # no ejecuta independientemente la simulación.
        # ==========================================================
        {
            "id": "TF-MC1",
            "tipo": "definicion",
            "sujeto": "Monte_Carlo_Cross_Term_Energy",
            "relacion": "reports",
            "objeto": "Term1_96.16_Term2_3.70_Term3_0.14",
            "polaridad": True,
            "cota": "3.70%",
            "depende_de": ["TF-A6"],
            "gobierna": ["constantes", "validacion"],
            "enunciado": (
                "EXPERIMENT 1: Cross Term Energy (Coupling P2 ↔ F3). "
                "Energy distribution in E² = α² · p² · c² + 2 · α · β · p · m · c³ + β² · m² · c⁴ "
                "with random exponential p and m (50,000,000 iterations): "
                "Term 1 (F3, kinetic): 96.16%. "
                "Term 2 (P2, cross): 3.70%. "
                "Term 3 (source, mass): 0.14%. "
                "Exact 2 · α · β: 0.071331 = 52/729. "
                "The cross term — the energy of the projection — represents 3.70% of the total energy on average. "
                "It is a small but structurally significant contribution (approx. 1 out of every 27 energy units). "
                "The exact analytical value is ≈ 3.6984%."
            ),
        },

        # ==========================================================
        # PART IV — MONTE CARLO SIMULATION
        # EXPERIMENT 2 — Beta as a Multidimensional Entity
        # ==========================================================
        {
            "id": "TF-MC2",
            "tipo": "definicion",
            "sujeto": "Monte_Carlo_Beta_Multidimensional",
            "relacion": "reports",
            "objeto": "beta_0D_1D_2D_3D_projections",
            "polaridad": True,
            "cota": "1/729",
            "depende_de": ["TF-B1"],
            "gobierna": ["constantes", "observador"],
            "enunciado": (
                "EXPERIMENT 2: Beta as a Multidimensional Entity. "
                "β 0D (point): 1/27 = 0.037037. "
                "β 1D (line): 1/3 = 0.333333. "
                "β 2D (plane): 1/9 = 0.111111. "
                "β 3D (volume): 1/27 = 0.037037. "
                "Relationship: β_1D × β_2D × β_3D = 1/(3 × 9 × 27) = 1/729 = β². "
                "And β² = 0.00137174. This is the same order of magnitude as ε² = 0.0007377. "
                "The product of beta's dimensional projections generates the observer's interference scale."
            ),
        },

        # ==========================================================
        # PART IV — MONTE CARLO SIMULATION
        # EXPERIMENT 6 — Only N=3 Produces a Functional Observer
        # ==========================================================
        {
            "id": "TF-MC6",
            "tipo": "definicion",
            "sujeto": "Monte_Carlo_N_equals_3_uniqueness",
            "relacion": "reports",
            "objeto": "N_3_is_the_only_integer_producing_physical_constants",
            "polaridad": True,
            "cota": None,
            "depende_de": [],
            "gobierna": ["constantes", "observador"],
            "enunciado": (
                "EXPERIMENT 6: Only N=3 Produces a Functional Observer. "
                "N=3 is the ONLY integer that simultaneously produces α⁻¹ ∼ 136.37 and m_e ∼ 0.51 MeV. "
                "For other integer values of N the resulting constants are non-physical."
            ),
        },
    ]


__all__ = ["CUERPO", "declaraciones"]
